<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>pylon_ros2_camera_wrapper</name>
  
  <version>1.1.0</version>
  
  <description>
    Wrapper loading pylon_ros2_camera component in a single process
  </description>
    
  <maintainer email="fpi@teknologisk.dk">Francois Picard</maintainer>
  
  <license>BSD</license>
  
  <url type="website">https://www.baslerweb.com/en/</url>
  <url type="repository">https://github.com/basler/pylon-ros-camera</url>
  <url type="bugtracker">https://github.com/basler/pylon-ros-camera/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>pylon_ros2_camera_component</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rcutils</depend>

<!-- For the test action client nodes -->
  <test_depend>cv_bridge</test_depend>
  <test_depend>image_geometry</test_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  
</package>
