#! /usr/bin/env python

import sys
import django
from toru_db_definition.models import IntrinsicCalibration

if "setup" in dir(django):
    django.setup()

if __name__ == "__main__":

    if len(sys.argv) == 1:
        print "USAGE: load_calib camera_name"
        exit(1)
    try:
        print IntrinsicCalibration.objects.get(device_name=sys.argv[1]).data
    except Exception as e:
        print "Fail for name '"+sys.argv[1]+"': ", e
    exit(0)

