# Used by :
# - set_Image_Encoding ROS service. (value = mono8, mono16, bgr8, rgb8, bayer_bggr8, bayer_gbrg8, bayer_rggb8, bayer_grbg8, bayer_rggb16, bayer_bggr16, bayer_gbrg16, bayer_grbg16).

string value 		# value to be setted
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages